// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/create-admin-user": {
            "post": {
                "description": "관리자 어드민 계정 생성 API",
                "tags": [
                    "Auth"
                ],
                "summary": "(관리자) 어드민 계정 생성",
                "parameters": [
                    {
                        "description": "어드민 생성 요청",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUserRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/careers/job-postings": {
            "get": {
                "description": "공고 목록을 활성화 상태, 페이지네이션 QueryString 옵션으로 가져옵니다.",
                "tags": [
                    "Careers"
                ],
                "summary": "(공통) 모집 공고 목록 조회",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "공고 활성화 상태",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "요청 페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "한번에 받을 페이지의 사이즈",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.JobPostingListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "관리자 모집 공고 생성 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 모집 공고 생성",
                "parameters": [
                    {
                        "description": "요청 Body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.JobPostingRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/careers/job-postings/{id}": {
            "get": {
                "description": "사용자 모집 공고 상세 조회 API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Careers"
                ],
                "summary": "(사용자) 모집 공고 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "요청 공고",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.AdminUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.JobPostingListResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.JobPostingResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.JobPostingRequest": {
            "type": "object",
            "properties": {
                "Department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "position_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.JobPostingResponse": {
            "type": "object",
            "properties": {
                "application_count": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "position_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "뽑기팡 API",
	Description:      "뽑기팡 Spine 애플리케이션",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
