// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/create-admin-user": {
            "post": {
                "description": "관리자 어드민 계정 생성 API",
                "tags": [
                    "Auth"
                ],
                "summary": "(관리자) 어드민 계정 생성",
                "parameters": [
                    {
                        "description": "어드민 생성 요청",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminUserRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh Token으로 Access Token 재발급을 진행합니다.",
                "tags": [
                    "Auth"
                ],
                "summary": "Access Token 재발급",
                "responses": {}
            }
        },
        "/careers/applications": {
            "get": {
                "description": "관리자 지원서 목록 조회 API",
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 지원서 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "찾을 공고 ID",
                        "name": "jobPostingId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "지원서 상태",
                        "name": "status",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "한번에 가져올 목록의 개수",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ApplicationListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "사용자 지원서 제출 API",
                "tags": [
                    "Careers"
                ],
                "summary": "(사용자) 지원서 제출",
                "parameters": [
                    {
                        "description": "지원서 요청 Body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateApplicationRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/careers/applications/{id}": {
            "get": {
                "description": "관리자 지원서 상세 조회 API",
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 지원서 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "지원서 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ApplicationResponse"
                        }
                    }
                }
            }
        },
        "/careers/job-postings": {
            "get": {
                "description": "공고 목록을 활성화 상태, 페이지네이션 QueryString 옵션으로 가져옵니다.",
                "tags": [
                    "Careers"
                ],
                "summary": "(공통) 모집 공고 목록 조회",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "공고 활성화 상태",
                        "name": "isActive",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "요청 페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "한번에 받을 페이지의 사이즈",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.JobPostingListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "관리자 모집 공고 생성 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 모집 공고 생성",
                "parameters": [
                    {
                        "description": "요청 Body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.JobPostingRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/careers/job-postings/{id}": {
            "get": {
                "description": "사용자 모집 공고 상세 조회 API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Careers"
                ],
                "summary": "(사용자) 모집 공고 상세 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "요청 공고",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "관리자 모집 공고 삭제 API",
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 모집 공고 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "삭제할 공고의 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "description": "관리자 모집 공고 수정 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Careers"
                ],
                "summary": "(관리자) 모집 공고 수정",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "수정할 공고의 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "요청 Body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.JobPostingModifyRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/certifications/checkin": {
            "post": {
                "description": "방문 인증을 생성하고 보상(EXP, 레벨, 스탬프, 배지)을 반환합니다.",
                "tags": [
                    "Certifications"
                ],
                "summary": "(사용자) 방문 인증 생성",
                "parameters": [
                    {
                        "description": "방문 생성 요청 DTO",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCheckInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CertificationResponse"
                        }
                    }
                }
            }
        },
        "/commons/file-uploads": {
            "post": {
                "description": "파일 업로드 API",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Commons"
                ],
                "summary": "(공통) 파일 업로드",
                "parameters": [
                    {
                        "type": "file",
                        "description": "업로드할 파일들",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gamification/achievement/main": {
            "get": {
                "description": "맵 화면에서 가장 최근의 미해결된 업적의 진행상황을 조회하는 API입니다.",
                "tags": [
                    "Gamification"
                ],
                "summary": "(사용자) 가장 최근의 미해결 업적 진행상황 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GamificationMainAchievementResponse"
                        }
                    }
                }
            }
        },
        "/stores/details/{storeId}": {
            "get": {
                "description": "사용자 가게 정보 API입니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(사용자) 가게 상세 페이지 가게정보 탭",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "스토어 ID",
                        "name": "storeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreDetailResponse"
                        }
                    }
                }
            }
        },
        "/stores/in-bounds": {
            "get": {
                "description": "지도 바운즈(북/남/동/서) 좌표로 매장 목록을 키워드로 조회합니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(공통) 영역 내 매장 조회",
                "parameters": [
                    {
                        "type": "number",
                        "description": "북쪽 위도",
                        "name": "north",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "남쪽 위도",
                        "name": "south",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "동쪽 경도",
                        "name": "east",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "서쪽 경도",
                        "name": "west",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "필터(all|scrapped|popular|recent_cert)",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FindInBoundsDto"
                        }
                    }
                }
            }
        },
        "/stores/nearby": {
            "get": {
                "description": "위도/경도 기준으로 주변 매장 목록을 페이지네이션과 키워드로 조회합니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(공통) 주변 매장 조회",
                "parameters": [
                    {
                        "type": "number",
                        "description": "기준 위도",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "기준 경도",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "검색 반경(미터)",
                        "name": "radius",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "필터(all|scrapped|popular|recent_cert)",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "요청 페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "한번에 받을 페이지의 사이즈",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FindNearByDto"
                        }
                    }
                }
            }
        },
        "/stores/reviews/{storeId}": {
            "get": {
                "description": "가세 상세 페이지 리뷰 API입니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(사용자) 가게 상세 페이지 리뷰 탭",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "스토어 ID",
                        "name": "storeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreReviewResponse"
                        }
                    }
                }
            }
        },
        "/stores/search": {
            "get": {
                "description": "사용자 가게 검색 API입니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(사용자) 가게 검색",
                "parameters": [
                    {
                        "type": "number",
                        "format": "float64",
                        "description": "위도",
                        "name": "latitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "format": "float64",
                        "description": "경도",
                        "name": "longitude",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "요청 페이지 번호",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "한번에 받을 페이지의 사이즈",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreSearchResponse"
                        }
                    }
                }
            }
        },
        "/stores/summary/{storeId}": {
            "get": {
                "description": "사용자 가게 기본 정보 API입니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(사용자) 가게 기본 정보",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "스토어 ID",
                        "name": "storeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreSummaryResponse"
                        }
                    }
                }
            }
        },
        "/stores/visits/{storeId}": {
            "get": {
                "description": "사용자 방문 내역 API입니다.",
                "tags": [
                    "Stores"
                ],
                "summary": "(사용자) 가게 상세 페이지 방문내역 탭",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "스토어 ID",
                        "name": "storeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VisitHistoryResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AchievementProgressResponse": {
            "type": "object",
            "properties": {
                "achievementId": {
                    "type": "integer",
                    "example": 101
                },
                "actionLabel": {
                    "type": "string",
                    "example": "4일 더 접속"
                },
                "badgeImageName": {
                    "type": "string",
                    "example": "badge_login_7.png"
                },
                "code": {
                    "type": "string",
                    "example": "LOGIN_STREAK"
                },
                "description": {
                    "type": "string",
                    "example": "7일 연속으로 접속하세요"
                },
                "earnedAt": {
                    "type": "string",
                    "example": "2024-01-10T08:15:00Z"
                },
                "isCompleted": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "연속 접속 7일"
                },
                "progressCurrent": {
                    "type": "integer",
                    "example": 3
                },
                "progressTarget": {
                    "type": "integer",
                    "example": 7
                },
                "remaining": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "dto.AdminUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@ppopgipang.com"
                },
                "nickname": {
                    "type": "string",
                    "example": "관리자"
                },
                "password": {
                    "type": "string",
                    "example": "P@ssw0rd123!"
                }
            }
        },
        "dto.ApplicationJobPosting": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 101
                },
                "title": {
                    "type": "string",
                    "example": "백엔드 엔지니어"
                }
            }
        },
        "dto.ApplicationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ApplicationResponse"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 58
                }
            }
        },
        "dto.ApplicationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-03-01T10:20:30Z"
                },
                "email": {
                    "type": "string",
                    "example": "minsoo.kim@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 501
                },
                "job_posting_response": {
                    "$ref": "#/definitions/dto.ApplicationJobPosting"
                },
                "memo": {
                    "type": "string",
                    "example": "백엔드 경력 5년"
                },
                "name": {
                    "type": "string",
                    "example": "김민수"
                },
                "phone": {
                    "type": "string",
                    "example": "010-1234-5678"
                },
                "resume_file_name": {
                    "type": "string",
                    "example": "resume.pdf"
                },
                "status": {
                    "type": "string",
                    "example": "접수"
                }
            }
        },
        "dto.CertificationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1001
                },
                "rewards": {
                    "$ref": "#/definitions/dto.RewardResponse"
                },
                "type": {
                    "type": "string",
                    "example": "loot"
                }
            }
        },
        "dto.CreateApplicationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "minsoo.kim@example.com"
                },
                "job_posting_id": {
                    "type": "integer",
                    "example": 101
                },
                "memo": {
                    "type": "string",
                    "example": "백엔드 경력 5년입니다."
                },
                "name": {
                    "type": "string",
                    "example": "김민수"
                },
                "phone": {
                    "type": "string",
                    "example": "010-1234-5678"
                },
                "resume_file_name": {
                    "type": "string",
                    "example": "resume.pdf"
                }
            }
        },
        "dto.CreateCheckInRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 37.498
                },
                "longitude": {
                    "type": "number",
                    "example": 127.0276
                },
                "rating": {
                    "type": "string",
                    "example": "good"
                },
                "reason_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "store_id": {
                    "type": "integer",
                    "example": 2001
                }
            }
        },
        "dto.FindInBoundsDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StoreInBoundsResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.FindNearByDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StoreFindNearByResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.GamificationMainAchievementResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/dto.AchievementProgressResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.JobPostingListResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.JobPostingResponse"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "dto.JobPostingModifyRequest": {
            "type": "object",
            "properties": {
                "Department": {
                    "type": "string",
                    "example": "플랫폼팀"
                },
                "description": {
                    "type": "string",
                    "example": "대규모 트래픽 환경에서 API를 설계하고 운영합니다."
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "서울"
                },
                "position_type": {
                    "type": "string",
                    "example": "정규직"
                },
                "title": {
                    "type": "string",
                    "example": "시니어 백엔드 엔지니어"
                }
            }
        },
        "dto.JobPostingRequest": {
            "type": "object",
            "properties": {
                "Department": {
                    "type": "string",
                    "example": "개발팀"
                },
                "description": {
                    "type": "string",
                    "example": "확장 가능한 API를 구축하고 운영합니다."
                },
                "location": {
                    "type": "string",
                    "example": "서울"
                },
                "position_type": {
                    "type": "string",
                    "example": "정규직"
                },
                "title": {
                    "type": "string",
                    "example": "백엔드 엔지니어"
                }
            }
        },
        "dto.JobPostingResponse": {
            "type": "object",
            "properties": {
                "application_count": {
                    "type": "integer",
                    "example": 12
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-02T15:04:05Z"
                },
                "department": {
                    "type": "string",
                    "example": "개발팀"
                },
                "description": {
                    "type": "string",
                    "example": "확장 가능한 API를 구축하고 운영합니다."
                },
                "id": {
                    "type": "integer",
                    "example": 101
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "location": {
                    "type": "string",
                    "example": "서울"
                },
                "position_type": {
                    "type": "string",
                    "example": "정규직"
                },
                "title": {
                    "type": "string",
                    "example": "백엔드 엔지니어"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-10T09:30:00Z"
                }
            }
        },
        "dto.Meta": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "dto.MyStat": {
            "type": "object",
            "properties": {
                "visit_count": {
                    "type": "integer"
                }
            }
        },
        "dto.NewBadgeResponse": {
            "type": "object",
            "properties": {
                "badge_image_name": {
                    "type": "string",
                    "example": "badge_first_certification.png"
                },
                "code": {
                    "type": "string",
                    "example": "FIRST_CERTIFICATION"
                },
                "description": {
                    "type": "string",
                    "example": "첫 인증을 완료했어요"
                },
                "id": {
                    "type": "integer",
                    "example": 4001
                },
                "name": {
                    "type": "string",
                    "example": "첫 인증"
                }
            }
        },
        "dto.OtherUserStat": {
            "type": "object",
            "properties": {
                "average_visit_count": {
                    "type": "integer"
                },
                "max_visit_count": {
                    "type": "integer"
                },
                "monthly_visitor_count": {
                    "type": "integer"
                }
            }
        },
        "dto.ReviewResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rating": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.RewardResponse": {
            "type": "object",
            "properties": {
                "current_level": {
                    "type": "integer",
                    "example": 5
                },
                "exp": {
                    "type": "integer",
                    "example": 50
                },
                "exp_to_next_level": {
                    "type": "integer",
                    "example": 150
                },
                "level_up": {
                    "type": "boolean",
                    "example": true
                },
                "new_badges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NewBadgeResponse"
                    }
                },
                "new_level": {
                    "type": "integer",
                    "example": 6
                },
                "new_stamp": {
                    "$ref": "#/definitions/dto.StampResponse"
                },
                "total_exp": {
                    "type": "integer",
                    "example": 1250
                }
            }
        },
        "dto.StampResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 3001
                },
                "image_name": {
                    "type": "string",
                    "example": "stamp_3001.png"
                },
                "store_name": {
                    "type": "string",
                    "example": "뽑기팡 강남점"
                }
            }
        },
        "dto.StoreDetailResponse": {
            "type": "object",
            "properties": {
                "is_bookmark": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "store_facility_response": {
                    "$ref": "#/definitions/dto.StoreFacilityResponse"
                },
                "store_opening_hour_responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StoreOpeningHourResponse"
                    }
                }
            }
        },
        "dto.StoreFacilityResponse": {
            "type": "object",
            "properties": {
                "machine_count": {
                    "type": "integer"
                },
                "payment_methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.StoreFindNearByResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "서울 강남구 강남대로 123"
                },
                "average_rating": {
                    "type": "number",
                    "example": 4.5
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-10T08:15:00Z"
                },
                "distance": {
                    "type": "integer",
                    "example": 350
                },
                "id": {
                    "type": "integer",
                    "example": 2001
                },
                "latitude": {
                    "type": "number",
                    "example": 37.498
                },
                "longitude": {
                    "type": "number",
                    "example": 127.0276
                },
                "name": {
                    "type": "string",
                    "example": "뽑기팡"
                },
                "phone": {
                    "type": "string",
                    "example": "02-123-4567"
                },
                "recent_review": {
                    "type": "string",
                    "example": "뽑기가 잘 뽑혀요"
                },
                "region1": {
                    "type": "string",
                    "example": "서울"
                },
                "region2": {
                    "type": "string",
                    "example": "강남구"
                },
                "review_count": {
                    "type": "integer",
                    "example": 27
                },
                "type": {
                    "$ref": "#/definitions/dto.StoreTypeResponse"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-05T12:00:00Z"
                }
            }
        },
        "dto.StoreInBoundsResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "서울 마포구 마포대로 45"
                },
                "average_rating": {
                    "type": "number",
                    "example": 4.2
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-12T09:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 2002
                },
                "latitude": {
                    "type": "number",
                    "example": 37.541
                },
                "longitude": {
                    "type": "number",
                    "example": 126.951
                },
                "name": {
                    "type": "string",
                    "example": "뽑기팡"
                },
                "phone": {
                    "type": "string",
                    "example": "02-987-6543"
                },
                "recent_review": {
                    "type": "string",
                    "example": "뽑기가 잘 뽑혀요"
                },
                "region1": {
                    "type": "string",
                    "example": "서울"
                },
                "region2": {
                    "type": "string",
                    "example": "마포구"
                },
                "review_count": {
                    "type": "integer",
                    "example": 18
                },
                "type": {
                    "$ref": "#/definitions/dto.StoreTypeResponse"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-07T14:30:00Z"
                }
            }
        },
        "dto.StoreOpeningHourResponse": {
            "type": "object",
            "properties": {
                "closeTime": {
                    "type": "string"
                },
                "dayOfWeek": {
                    "type": "integer",
                    "format": "int32"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "isClosed": {
                    "type": "boolean"
                },
                "openTime": {
                    "type": "string"
                }
            }
        },
        "dto.StoreResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "서울 강남구 테헤란로 10"
                },
                "average_rating": {
                    "type": "number",
                    "example": 4
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "distance": {
                    "type": "integer",
                    "example": 120
                },
                "id": {
                    "type": "integer",
                    "example": 2000
                },
                "latitude": {
                    "type": "number",
                    "example": 37.5
                },
                "longitude": {
                    "type": "number",
                    "example": 127.035
                },
                "name": {
                    "type": "string",
                    "example": "뽑기팡 매장"
                },
                "phone": {
                    "type": "string",
                    "example": "02-555-1234"
                },
                "region1": {
                    "type": "string",
                    "example": "서울"
                },
                "region2": {
                    "type": "string",
                    "example": "강남구"
                },
                "thumbnail_name": {
                    "type": "string",
                    "example": "store_thumbnail_2000.jpg"
                },
                "type": {
                    "$ref": "#/definitions/dto.StoreTypeResponse"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-01T00:00:00Z"
                }
            }
        },
        "dto.StoreReviewResponse": {
            "type": "object",
            "properties": {
                "review_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reviews_responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewResponse"
                    }
                }
            }
        },
        "dto.StoreSearchResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StoreResponse"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/dto.Meta"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.StoreSummaryResponse": {
            "type": "object",
            "properties": {
                "average_rating": {
                    "type": "number",
                    "example": 4
                },
                "id": {
                    "type": "integer",
                    "example": 2000
                },
                "image_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "뽑기팡 매장"
                },
                "review_count": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.StoreTypeResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "커피와 디저트"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "카페"
                }
            }
        },
        "dto.VisitHistoryResponse": {
            "type": "object",
            "properties": {
                "my_stat": {
                    "$ref": "#/definitions/dto.MyStat"
                },
                "other_user_stat": {
                    "$ref": "#/definitions/dto.OtherUserStat"
                },
                "review_images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reviews_responses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "뽑기팡 API",
	Description:      "뽑기팡 Spine 애플리케이션",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
